# Common build stage
FROM node:14

COPY . ./app

WORKDIR /app

RUN npm install

EXPOSE 8888

# Dvelopment build stage
#FROM common-build-stage as development-build-stage

ENV NODE_ENV development

CMD ["npm", "run", "dev"]
