@hostname = localhost
@port = 8888
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###

@name = order

POST http://{{host}}/api/{{name}} HTTP/1.1
content-type: {{contentType}}
  
{
    "userId": "잘들어가나보자@gmail.com",
    "productId": "OR_5278bc4ba1300524dd3fa8db8fd0a9d9",
    "startDateTime": "2021-05-30 04:47",
    "endDateTime": "-",
    "orderState": "주문입력"
}

###

GET  http://{{host}}/api/{{name}}/test@gmail.com HTTP/1.1

###

GET  http://{{host}}/api/{{name}}/pay/test@gmail.com HTTP/1.1
