@hostname = localhost
@port = 8888
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###

@name = point

PUT http://{{host}}/api/{{name}} HTTP/1.1
content-type: {{contentType}}
  
{
    "userId": "test@gmail.com",
    "pointId": "PT0001",
    "score": "30",
    "regDate": "2021-05-30 04:47"
}

###

PUT http://{{host}}/api/{{name}}/add HTTP/1.1
content-type: {{contentType}}
  
{
    "userId": "test@gmail.com",
    "pointId": "PT0001",
    "score": "30",
    "regDate": "2021-05-30 04:47"
}

###

GET  http://{{host}}/api/{{name}}/test@gmail.com HTTP/1.1

###
